### ISSUE TITLE
缺一个显示代码的功能

### ISSUE THREAD

**Issue by Mrokor** [wangjinxin613/uni-jin#2]
缺一个显示代码的功能

**Comment by wangjinxin613** [comment]
写代码的功能吗

**Comment by i5920** [comment]
是的，而且你这个在微信报错



---原始邮件---
发件人: "王金鑫"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 晚上7:23
收件人: "wangjinxin613/uni-jin"<uni-jin@noreply.github.com&gt;;
抄送: "OkCoder"<1046512080@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangjinxin613/uni-jin] 缺一个显示代码的功能 (#2)




 
写代码的功能吗

**Comment by wangjinxin613** [comment]
报啥错啊

**Comment by i5920** [comment]
@ready里面的方法不是一个函数



---原始邮件---
发件人: "王金鑫"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 晚上8:02
收件人: "wangjinxin613/uni-jin"<uni-jin@noreply.github.com&gt;;
抄送: "OkCoder"<1046512080@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wangjinxin613/uni-jin] 缺一个显示代码的功能 (#2)




 
报啥错啊

**Comment by wangjinxin613** [comment]
我的没有报错啊
